import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ProviderForSession from "@/providers/ProviderForSession";
import ProviderForRecoil from "@/providers/ProviderForRecoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProviderForSession>
            <ProviderForRecoil>
                <html lang="en">
                    <body className={inter.className}>
                        <Header />
                        {children}
                    </body>
                </html>
            </ProviderForRecoil>
        </ProviderForSession>
    );
}
